version: '3.7'

networks:
  recraft:
    external: false

volumes:
  spigot:

services:
  spigot:
    build:
      context: .
      dockerfile: ./docker/spigot/Dockerfile
    image: spigot
    networks:
      - recraft
    volumes:
      - spigot:/spigot
    ports:
      - "25565:25565"
    stdin_open: true
