version: '3.7'

networks:
  recraft:
    external: false

volumes:
  spigot:
  bungee:


services:
  spigot:
    build:
      context: .
      dockerfile: ./docker/spigot/Dockerfile
    image: spigot
    networks:
      - recraft
    volumes:
      - spigot:/spigot
    ports:
      - "25566:25566"
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  bungee:
    build:
      context: .
      dockerfile: ./docker/bungee/Dockerfile
    image: bungee
    networks:
      - recraft
    volumes:
      - bungee:/bungee
    ports:
      - "25570:25570"
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
