name: Annihilation
version: 0.0.1
main: net.recraft.annihilatoin.Main
api-version: 1.8.9
depend: [ProtocolLib]
commands:
  vote:
    description: マップの投票を行う
    usage: /<command> [gameMap]
  teleport:
    description: 指定したチームの色の場所の特殊な地点に飛ぶ
    usage: /<command> [team] [nexus | enderchest | enderfurnace| spawn1,2,3]
  team:
    description:
    usage: /<command> team [red | blue | yello| green]
  anniconfig:
    description: maps.yamlにチームごとのブロックを設定する
    usage: /<command>
  kit:
    description: kitを設定できる
    usage: /<command>
  statics:
    description: 統計を見れる
    usage: /<command>
  protectBase:
    description: 統計を見れる
    usage: /<command>
  gm:
    description: 統計を見れる
    usage: /<command>